language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=~/tinywatch/src/tinywatch

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  
  - wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip
  - unzip tools_r25.2.3-linux.zip -d ~/android-sdk-linux
install:

  - sudo apt-get -y install openjdk-7-jre
  - ~/android-sdk-linux/tools/android list sdk -a
  - printf 'y' | ~/android-sdk-linux/tools/android update sdk -a -u -t "platform-tool,android-25,build-tools-25.0.0"
  - printf 'y' | ~/android-sdk-linux/tools/bin/sdkmanager "platforms;android-24"
  - export PATH=$PATH:~/android-sdk-linux/platform-tools:~/android-sdk-linux/tools:~/android-sdk-linux/build-tools/25.0.0/
  - source ~/.bashrc

  - sudo apt-get install libc6:i386 libstdc++6:i386
  - sudo apt-get install zlib1g:i386
  - . ~/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g cordova

  - platformio lib -g install "TinyScreen"

  - wget https://github.com/cbolgiano/tinywatch/archive/develop.zip
  - unzip develop.zip -d ~/tinywatch
  - ln -s $PWD ~/tinywatch
  - unzip $PWD/libs/arduino-BLEPeripheral-master.zip -d /tiny-libs
  - unzip $PWD/libs/Time-master.zip -d /tiny-libs
  - unzip $PWD/libs/tinywatch-time.zip -d /tiny-libs

script:
  - platformio ci --lib="TinyScreen" --lib="/tiny-libs" --board=zero
  - cd $PWD/app/tinywatch && cordova build android