language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.13-linux64.tar.xz
  - tar xf arduino-1.6.13-linux64.tar.xz
  - sudo mv arduino-1.6.13 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g cordova
install:
  - arduino --pref "boardsmanager.additional.urls=http://files.tinycircuits.com/ArduinoBoards/package_tinycircuits_index.json" --save-prefs
  - arduino --pref "custom_BuildOption=tinyscreen_normal" --save-prefs
  - arduino --install-boards arduino:samd --save-prefs
  - arduino --install-boards TinyCircuits:samd --save-prefs
  - arduino --install-library "TinyScreen" --save-prefs
  - wget https://github.com/cbolgiano/tinywatch/archive/develop.zip
  - unzip develop.zip -d ~/tinywatch
  - ln -s $PWD ~/tinywatch
  - unzip $PWD/libs/td2play.zip -d /usr/local/share/arduino/libraries
  - unzip $PWD/libs/arduino-BLEPeripheral-master.zip -d /usr/local/share/arduino/libraries
script:
  - arduino --verify --board TinyCircuits:samd:tinyscreen $PWD/tinywatch.ino
  - cd $PWD/app/tinywatch && cordova build android
